### ISSUE TITLE
Suggest Higher Gas

### ISSUE THREAD

**Issue by drakedanner** [FlipsideCrypto/badger#12]
Ensure transactions go through quickly

**Comment by nftchance** [comment]
There is something to look into here. Since EIP-1559, we would not be changing the amount of gas for speed to handle the issue of when the network is under extreme loads. We don't need all transactions to go through fast, that will be a retained control of the user however, we do need the ability for the transaction to go through even when the chain the organization is on is doing something weird gas-wise.

Previously, the simplest solution would have been to do something like a `1.03` multiplier however that doesn't make sense anymore. Will figure this out and ensure a solution has been implemented before the next major version release.

**Comment by masonchain** [comment]
Not entirely sure the best way to handle this either but this [end point](https://gasstation-mainnet.matic.network/v2) provides the slow/medium/fast presets. We could just auto suggest fast?

**Comment by masonchain** [comment]
Polygon fees are officially messed up. Getting fee data with an ethers provider always returns maxPriorityFeePerGas as 2.5, yet priority fee is the thing that varies most on Polygon.

This is a comment from an ethers maintainer:

![Image](https://user-images.githubusercontent.com/33527785/196808848-b87a9c2c-fbe9-4320-b8f3-9f90272f32ad.png)

The Priority Fee setting is what has been causing the transaction underpriced issue, and it seems even the default Metamask RPC gas estimation (and our Alchemy provider) has not accounted for Polygon's boofed way of handling things.

I can get the max total fee and set our max priority fee to the same, but we end up costing our users more in the long run. This is the for now solution as we cannot get an accurate priority fee from providers.

**Comment by masonchain** [comment]
https://github.com/FlipsideCrypto/badger/pull/36

Just suggesting gas price is functional.
