### ISSUE TITLE
Fix: Docs subdomain

### ISSUE THREAD

**Issue by masonchain** [FlipsideCrypto/badger#136]
https://docs.trybadger.com/ is linked in various places (The one pager pitch and the Cosa subsidized public goods page), but leads to a dead link. We should have this redirect to our [Gitbook](https://flipside-crypto.gitbook.io/badger/what-is-badger) until if/when we directly create a documentation page.

**Comment by nftchance** [comment]
SSL is not relative to DNS, it is relative to it's hosting.

If you go to a redirect (unhosted website) then there is no hosting engine for it to resolve DNS to.

Thus, http://docs.trybadger.com works because the redirect is set, however there is no an SSL-level redirect engine on domains that don't exist
