### ISSUE TITLE
Bug: Badge Update Page

### ISSUE THREAD

**Issue by drakedanner** [FlipsideCrypto/badger#151]
![image](https://user-images.githubusercontent.com/11461756/202534751-74a77081-7277-4932-afe9-aea56dde17e2.png)
![image](https://user-images.githubusercontent.com/11461756/202534764-d674d7a5-96c5-4eb0-a52c-e1724c90e918.png)

possible bug on the Update Badge page.

(On our end we don't need to change existing badge metadata just yet -- testing for the future.)

The error shows up right away when the page is opened. For testing purposes I tried to change some of the description text and confirm the update -- but the Update button at the bottom remains grayed out.

**Comment by masonchain** [comment]
Addressed in the latest push to main.

The problem arose from Managers being brought into the edit form and on the backend users/wallets are not just a string of address but a User object. The Manager field was then just filled with objects and not strings like normal.

I removed the Manager array field from editing because it would be more confusing to include it IMO. You can't remove Managers in the edit badge function, so it would make for bad UX for a user to remove managers there and it not reflect, as well as waste gas feeding in the managers that would not be changing into the function.
