### ISSUE TITLE
Feature: Source collection and badge data on page

### ISSUE THREAD

**Issue by masonchain** [FlipsideCrypto/badger#26]

**Comment by masonchain** [comment]
Figure out where we're going to pull these fields from.

Net Worth field will probably be disabled for the time being unless we stumble upon a dope way to source it.

![Image](https://user-images.githubusercontent.com/33527785/196527162-99e0adf4-e06e-4912-b5ea-d81018626ae0.png)
![Image](https://user-images.githubusercontent.com/33527785/196527163-37958203-885a-4859-b0d1-d8c2a2cbd24a.png)

**Comment by nftchance** [comment]
Hmmm interesting, I imagined we could partner with someone like DefiLlama if we don't want to write our own.

**Comment by nftchance** [comment]
For this, we will be using DefiLlamas API. Ideally, because they are such an incredible and productive member of the ecosystem, we will be able to spotlight that they are the data source for this material.

Right now, the current design does not handle that, but it will eventually. For now, we will utilize the API. If needed, I can write the aggregation logic for the front end. Potentially even this could be stuffed into the backend.
