### ISSUE TITLE
Fix: trybadger.com

### ISSUE THREAD

**Issue by drakedanner** [FlipsideCrypto/badger#53]
Set up trybadger.com as the primary address for the Badger application.

Re-direct trybadger.xyz, badger.utc24.io, and other other worthwhile URLs we own to trybadger.com

**Comment by nftchance** [comment]
It turns out that Fly has made back-ends extremely easy however they just do not specialize in static sites / front ends without massaging them to fit within their machine. It is doable but less than ideal, and the front-end needs no real change beyond a domain update.

Going to continue using Netlify for the front end and Fly for back end only.
