### ISSUE TITLE
Fix: Unclear Manager UX

### ISSUE THREAD

**Issue by nftchance** [FlipsideCrypto/badger#98]
![Image](https://user-images.githubusercontent.com/22061495/197900804-72b9bac6-8e8f-4e8e-b93e-fab5cd529309.png)

**Comment by masonchain** [comment]
This will be fixed in this PR. See attached comment for concerns about a 2 button click solution for the tx issues.

(IMO, yes the trash can should be present for an empty field. Would be weird to have it appear as soon as you stop typing. And if it's the only field the trash button just clears the field.)
